Fixed Issue 3
swcarpentry-ja/2021-04-02-todai-online-ja pull request #8
Opened 2021-02-28 13:02 UTC by naganeayu

Fixed #3

2021-03-01 01:22 UTC, joelnitta requested changes
I forgot to mention we have already translated the titles for these in the [R lesson](https://swcarpentry-ja.github.io/r-novice-gapminder/ja/). Please use those titles as follows in the suggestions.

2021-03-01 01:22 UTC, joelnitta commented on _includes/swc/schedule.html
> +      <tr> <td>10:10</td>  <td>RとRStudioの紹介</td> </tr>
```suggestion
      <tr> <td>10:10</td>  <td>RとRStudioの入門</td> </tr>
```

2021-03-01 01:22 UTC, joelnitta commented on _includes/swc/schedule.html
> +      <tr> <td>11:30</td>  <td>ヘルプの参照</td> </tr>
```suggestion
      <tr> <td>11:30</td>  <td>ヘルプ機能</td> </tr>
```

2021-03-01 01:22 UTC, joelnitta commented on _includes/swc/schedule.html
> +      <tr> <td>11:10</td>  <td>データフレームの探索</td> </tr>
```suggestion
      <tr> <td>11:10</td>  <td>データフレームの内容を確認</td> </tr>
```

2021-03-01 01:22 UTC, joelnitta commented on _includes/swc/schedule.html
> +      <tr> <td>10:00</td>  <td>データのサブセッティング</td> </tr>
```suggestion
      <tr> <td>10:00</td>  <td>データの部分集合化</td> </tr>
```

2021-03-01 01:22 UTC, joelnitta commented on _includes/swc/schedule.html
> +      <tr> <td>11:10</td>  <td>ggplot2を使用した出版物並みの品質のグラフィックの作成</td> </tr>
I actually like this translation more! Perhaps we should change the episode title in the lesson, 「ggplot2 を用いたパブリッシュ出来る品質のグラフィックスの作成」to match?

とりあえずそのままでお願いします。

2021-03-01 01:22 UTC, joelnitta commented on _includes/swc/schedule.html
> +      <tr> <td>11:10</td>  <td>knitrを使用したレポート作成</td> </tr>
```suggestion
      <tr> <td>11:10</td>  <td>knitr によるレポートの作成</td> </tr>
```

2021-03-01 09:29 UTC, naganeayu commented
Thank you @joelnitta for suggestions!

2021-03-02 00:15 UTC, joelnitta approved these changes

2021-03-02 00:15 UTC, merged